---
- name: Checkout charts repo
  include_tasks: checkout_repo.yml
  vars:
    repo_dir: charts-repo-temp
    repo_url: "{{ baremetal_repo_url }}"
    repo_branch: "{{ baremetal_branch }}"
    repo_pull_request: "{{ baremetal_pull_request | default('') }}"

- name: Organize charts repo
  include_tasks: organize_charts_repo_core.yml

- name: Create directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    mode: 0775
  with_items: "{{ directories_to_create }}"

- name: Generate SSH keypair
  community.crypto.openssh_keypair:
    type: ed25519
    path: ~/.ssh/id_ed25519
    regenerate: always
  register: ssh_key_gen_result

- name: Set node_ssh_public_key fact
  set_fact:
    node_ssh_public_key: "{{ ssh_key_gen_result.public_key }}"

- name: Create metal3 overrides yaml file
  template:
    src: "parent-chart-overrides.yaml.j2"
    dest: "~/parent-chart-overrides.yaml"
  register: template_parent_overrides

- name: Deploy helm components using file based overrides
  kubernetes.core.helm:
    name: metal3
    chart_ref: "~/charts/metal3"
    state: present
    release_namespace: metal-cubed
    values_files:
    - "~/parent-chart-overrides.yaml"
    atomic: yes
    create_namespace: yes
    timeout: 30m
