- block:
  - name: Add repos on openSUSE
    community.general.zypper_repository:
      repo: "{{ item }}"
      auto_import_keys: true
    when: ansible_facts['distribution'] == 'openSUSE Leap'
    loop: "{{ repos.opensuse }}"
  - name: Install required packages on {{ ansible_facts['distribution'] }}
    community.general.zypper:
      name: "{{ packages.opensuse }}"
      state: present
      force_resolution: true
    when: ansible_facts['distribution'] == 'openSUSE Leap'
  - name: Install required packages on {{ ansible_facts['distribution'] }}
    package:
      name: "{{ packages.ubuntu }}"
      state: present
    when: ansible_facts['distribution'] == 'Ubuntu'
  - name: Install pip packages
    pip:
      executable: "pip3"
      name: "{{ packages.pip3 }}"
      state: present
  become: true
