---
- name: Add metallb helm repo
  kubernetes.core.helm_repository:
    repo_url: "{{ metallb_helm_repo_url }}"
    name: "{{ metallb_helm_repo_name }}"

- name: Deploy metallb helm chart
  kubernetes.core.helm:
    name: "{{ metallb_release }}"
    chart_ref: "{{ metallb_helm_chart_ref }}"
    state: present
    release_namespace: "{{ metallb_namespace }}"
    atomic: yes
    timeout: 10m
    create_namespace: yes
  environment:
    HELM_EXPERIMENTAL_OCI: "1"

- name: Wait for metallb to be rolled out
  shell: >
    kubectl -n {{ metallb_namespace }} rollout status deploy/metallb-controller
  register: metallb_rollout_result
  retries: 5
  delay: 10
  until: "'successfully rolled out' in metallb_rollout_result.stdout"

- name: Create metallb ip-address-pool yaml file
  template:
    src: "ip-address-pool.yaml.j2"
    dest: "{{ working_dir }}/ip-address-pool.yaml"
  register: template_ip_address_pool

- name: Apply ip-address-pool
  shell: >-
    kubectl apply -f "{{ working_dir }}/ip-address-pool.yaml"
