---
- name: Install required packages
  include_role:
    name: vm
    tasks_from: install_suse_package
  vars:
    suse_packages: [python311, python311-pip, python311-devel, gcc]

- name: Select python althernative
  become: yes
  community.general.alternatives:
    name: python
    path: /usr/bin/python3.11
    priority: 1
    link: /usr/bin/python

- name: Select python3 althernative
  become: yes
  community.general.alternatives:
    name: python3
    path: /usr/bin/python3.11
    priority: 1
    link: /usr/bin/python3
