---
- name: Equinix Setup
  hosts: localhost
  become: true
  tasks: 
    - name: Define egress network
      become: yes
      command: virsh net-define "{{ ansible_env.HOME }}/metal3-demo/libvirt/egress.xml"

    - name: Start egress network
      become: yes
      command: virsh net-start egress
