---
- name: Checkout charts repo
  include_tasks: checkout_repo.yml
  vars:
    repo_dir: suse-edge
    repo_url: "{{ metal3_repo_url }}"
    repo_branch: "{{ metal3_branch }}"
    repo_pull_request: "{{ metal3_pull_request | default('') }}"

- name: Template manifest for additional CA cert
  template:
    src: tls-ca-additional.yaml.j2
    dest: "{{ working_dir }}/tls-ca-additional.yaml"
  vars:
    additional_ca_cert: "{{ lookup('ansible.builtin.file', image_cache_conf_dir + '/ca-certificate.pem') }}"

- name: Apply manifest for additional CA cert
  command:
    cmd: kubectl apply -f "{{ working_dir }}/tls-ca-additional.yaml"

- name: Create metal3 overrides yaml file
  template:
    src: "metal3-values.yaml.j2"
    dest: "{{ working_dir }}/charts/metal3-values.yaml"

- name: Deploy helm components using file based overrides
  kubernetes.core.helm:
    name: metal3
    chart_ref: "{{ working_dir }}/charts/suse-edge/charts/metal3/{{ metal3_chart_version }}"
    state: present
    release_namespace: "{{ metal3_namespace }}"
    values_files:
    - "{{ working_dir }}/charts/metal3-values.yaml"
    atomic: yes
    create_namespace: yes
    timeout: 12m
