---
- set_fact:
    generate_vm_nodes: "{{vm_nodes is not defined}}"

- name: Set an empty default for vm_nodes if not already defined
  set_fact:
    vm_nodes: []
  when: generate_vm_nodes

- name: Populate vm_nodes if not already defined
  when: generate_vm_nodes
  include_tasks: vm_nodes_tasks.yml
  loop: "{{libvirt_flavors|dict2items}}"
  loop_control:
    loop_var: flavor

- debug:
    msg: "vm_nodes={{vm_nodes}}"

- name: get a list of MACs to use
  generate_macs:
    nodes: "{{ vm_nodes }}"
    networks: "{{ libvirt_networks }}"
  register: node_mac_map
  when: vm_nodes | length > 0

- debug:
    msg: "node_mac_map={{node_mac_map}}"
