---
####################################################################
# Per https://docs.ranchermanager.rancher.io/pages-for-subheaders/ #
# install-upgrade-on-a-kubernetes-cluster                          #
####################################################################

- name: Add rancher helm repo
  kubernetes.core.helm_repository:
    repo_url: "{{ rancher_helm_repo_url }}"
    name: "{{ rancher_helm_repo_name }}"

- name: Deploy Rancher Helm chart
  kubernetes.core.helm:
    name: "{{ rancher_release }}"
    chart_ref: "{{ rancher_helm_chart_ref }}"
    chart_version: "{{ rancher_version }}"
    state: present
    release_namespace: "{{ rancher_namespace }}"
    values:
      installCRDs: true
      hostname: "{{ rancher_hostname }}"
      bootstrapPassword: "{{ rancher_bootstrap_password }}"
      replicas: "{{ rancher_replicas }}"
      extraEnv[0].name: CATTLE_SERVER_URL
      extraEnv[0].value: "https://{{ rancher_hostname }}"
    atomic: yes
    create_namespace: yes
  register: rancher_deploy_result
  until: rancher_deploy_result.failed == false
  retries: 3
  delay: 20

- name: Wait for rancher to be rolled out
  shell: >
    kubectl -n {{ rancher_namespace }} rollout status deploy/{{ rancher_release }}
  register: rancher_rollout_result
  retries: 5
  delay: 10
  until: "'successfully rolled out' in rancher_rollout_result.stdout"
