---
- name: Checkout local-path-provisioner repo
  include_role:
    name: metal3
    tasks_from: checkout_repo
  vars:
    repo_dir: local-path-provisioner
    repo_url: "{{ local_path_provisioner_repo_url }}"
    repo_branch: "{{ local_path_provisioner_branch }}"
    repo_pull_request: "{{ local_path_provisioner_pull_request | default('') }}"

- name: Deploy local-path-provisioner via helm
  kubernetes.core.helm:
    name: "{{ local_path_provisioner_release }}"
    chart_ref: "~/charts/local-path-provisioner/deploy/chart/local-path-provisioner"
    state: present
    release_namespace: "{{ local_path_provisioner_namespace }}"
    atomic: yes
    timeout: 10m
    create_namespace: yes
  environment:
    HELM_EXPERIMENTAL_OCI: "1"
