---
############################################################################
# Per https://cert-manager.io/docs/installation/helm/#installing-with-helm #
############################################################################

- name: Add cert-manager helm repo
  kubernetes.core.helm_repository:
    repo_url: "{{ cert_manager_helm_repo_url }}"
    name: "{{ cert_manager_helm_repo_name }}"

- name: Deploy cert-manager helm chart
  kubernetes.core.helm:
    name: "{{ cert_manager_release }}"
    chart_ref: "{{ cert_manager_helm_chart_ref }}"
    state: present
    release_namespace: "{{ cert_manager_namespace }}"
    values:
      installCRDs: true
      extraArgs: "{{ 'extraArgs={--dns01-recursive-nameservers-only,--dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53}' if dns_provider is defined and dns_provider == 'cloudflare' else '' }}"
    atomic: yes
    create_namespace: yes

- name: Wait for cert-manager to be rolled out
  shell: >
    kubectl -n {{ cert_manager_namespace }} rollout status deploy/{{ cert_manager_release }}
  register: cert_manager_rollout_result
  retries: 5
  delay: 10
  until: "'successfully rolled out' in cert_manager_rollout_result.stdout"
