---
- name: Prepare host prerequisites
  hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - name: Install required packages
      import_role:
        name: packages_installation
    - name: Install Kubernetes tools and utilities
      import_role:
        name: kubernetes-tools

