---
- hosts: localhost
  connection: local
  tasks:

    - name: Start Management Cluster VM
      include_role:
        name: management-cluster
      when:
        - (not do_not_install_vm | default(False)) | bool
      vars:
        vm_hostname: management-cluster
        vm_instance_name: management_0
        vm_network: "{{ management_cluster_vm_network }}"
        vm_public_network_ip: "{{ management_cluster_public_ip }}"

    - name: Show management-cluster vm IP
      debug:
        msg: "Login to the management-cluster vm with 'ssh {{ vm_user }}@{{ management_cluster_public_ip }}'"

    - name: Create .kube
      file:
        path: ~/.kube
        state: directory

    # TODO - there's likely a better way to do this...
    - name: Fetch kubeconfig from management cluster
      command:
        cmd: "ssh -o StrictHostKeyChecking=no {{ vm_user }}@{{ management_cluster_public_ip }} sudo cat /etc/rancher/rke2/rke2.yaml"
      register: kubeconfig

    - name: Write ~/.kube/config locally
      copy:
        content: "{{ kubeconfig.stdout }}"
        dest: ~/.kube/config

    - name: Update IP in kubeconfig
      replace:
        path: ~/.kube/config
        regexp: '127\.0\.0\.1'
        replace: "{{ management_cluster_public_ip }}"

    - name: Deploy cert-manager
      import_role:
        name: cert-manager

    - name: Deploy rancher
      import_role:
        name: rancher
      vars:
        rancher_hostname: management-cluster
        rancher_host_ip: "{{ management_cluster_public_ip }}"

    - name: Deploy local-path-provisioner
      import_role:
        name: local-path-provisioner

    - name: Deploy metallb
      import_role:
        name: metallb
      vars:
        management_cluster_ironic_ip: "{{ management_cluster_ironic_ip }}"

    - name: Deploy Metal3
      import_role:
        name: metal3

    - name: Deploy capi
      import_role:
        name: capi
