---
- hosts: localhost
  connection: local
  tasks:

    - name: Create VM
      include_role:
        name: vm
      when:
        - (not do_not_install_vm | default(False)) | bool
      vars:
        vm_hostname: management-cluster
        vm_instance_name: management-cluster
        vm_network: "{{ management_cluster_vm_network }}"
        vm_public_network_ip: "{{ management_cluster_public_ip }}"
        vm_libvirt_network_params: "{{ metal3_vm_libvirt_network_params }}"
        vm_memory: 16384
        vm_vcpus: 8

    - name: Show management-cluster vm IP
      debug:
        msg: "Login to the management-cluster vm with 'ssh {{ vm_user }}@{{ management_cluster_public_ip }}'"

    - name: Define management-cluster node
      ansible.builtin.add_host:
        ansible_python_interpreter: "{{ vm_python_interpreter | default('/usr/bin/python3') }}"
        name: management-cluster
        hostname: management-cluster
        ansible_user: "{{ vm_user }}"
        ansible_host: "{{ management_cluster_public_ip }}"
        groups:
          - "{{ management_clusterhost_group | default('management_cluster_group') }}"

- hosts: management-cluster
  tasks:
    - name: Deploy docker
      import_role:
        name: docker

    - name: Deploy RKE2
      import_role:
        name: rke2-server

    - name: Create .kube
      file:
        path: ~/.kube
        state: directory

    - name: Fetch kubeconfig from management cluster
      fetch:
        src: /home/{{ vm_user }}/.kube/config
        flat: true
        dest: ~/.kube/config

    - name: Install python-ironicclient
      import_role:
        name: ironicclient
      vars:
        public_ip: "{{ management_cluster_public_ip }}"

- hosts: localhost
  connection: local
  tasks:
    - name: Update IP in kubeconfig
      replace:
        path: ~/.kube/config
        regexp: '127\.0\.0\.1'
        replace: "{{ management_cluster_public_ip }}"

    - name: Deploy cert-manager
      import_role:
        name: cert-manager

    - name: Deploy rancher
      import_role:
        name: rancher
      vars:
        rancher_hostname: management-cluster
        rancher_host_ip: "{{ management_cluster_public_ip }}"

    - name: Deploy local-path-provisioner
      import_role:
        name: local-path-provisioner

    - name: Deploy metallb
      import_role:
        name: metallb
      vars:
        management_cluster_ironic_ip: "{{ management_cluster_ironic_ip }}"

    - name: Deploy capi
      import_role:
        name: capi

    - name: Deploy Metal3
      import_role:
        name: metal3
