---
- hosts: localhost
  connection: local
  tasks:

    - name: Create VM
      include_role:
        name: vm
      when:
        - (not do_not_install_vm | default(False)) | bool
      vars:
        vm_hostname: metal3-core
        vm_instance_name: metal3-core
        vm_network: "{{ metal3_core_vm_network }}"
        vm_public_network_ip: "{{ metal3_core_public_ip }}"
        vm_libvirt_network_params: "{{ metal3_vm_libvirt_network_params }}"
        vm_memory: 16384
        vm_vcpus: 8

    - name: Show metal3-core vm IP
      debug:
        msg: "Login to the metal3-core vm with 'ssh {{ vm_user }}@{{ metal3_core_public_ip }}'"

    - name: Define metal3-core node
      ansible.builtin.add_host:
        ansible_python_interpreter: "{{ vm_python_interpreter | default('/usr/bin/python3') }}"
        name: metal3-core
        hostname: metal3-core
        ansible_user: "{{ vm_user }}"
        ansible_host: "{{ metal3_core_public_ip }}"
        groups:
          - "{{ metal3_corehost_group | default('metal3_core_group') }}"

- hosts: metal3-core
  tasks:
    - name: Deploy docker
      import_role:
        name: docker

    - name: Deploy RKE2
      import_role:
        name: rke2-server

    - name: Create .kube
      file:
        path: ~/.kube
        state: directory

    - name: Fetch kubeconfig from management cluster
      fetch:
        src: /home/{{ vm_user }}/.kube/config
        flat: true
        dest: ~/.kube/config

    - name: Install python-ironicclient
      import_role:
        name: ironicclient
      vars:
        public_ip: "{{ metal3_core_public_ip }}"

- hosts: localhost
  connection: local
  tasks:
    - name: Update IP in kubeconfig
      replace:
        path: ~/.kube/config
        regexp: '127\.0\.0\.1'
        replace: "{{ metal3_core_public_ip }}"

    - name: Deploy cert-manager
      import_role:
        name: cert-manager

    - name: Deploy rancher
      import_role:
        name: rancher
      vars:
        rancher_hostname: metal3-core
        rancher_host_ip: "{{ metal3_core_public_ip }}"

    - name: Deploy local-path-provisioner
      import_role:
        name: local-path-provisioner

    - name: Deploy metallb
      import_role:
        name: metallb
      vars:
        metal3_core_ironic_ip: "{{ metal3_core_ironic_ip }}"

    - name: Deploy capi
      import_role:
        name: capi

    - name: Deploy Metal3
      import_role:
        name: baremetal
